name: integrated_vehicle_management_system
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sidebarx: ^0.16.2
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.13.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  firebase_messaging: ^14.7.10
  provider: ^6.1.1
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^10.7.0
  pdf: ^3.10.8
  printing: ^5.12.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
